spring:
  application:
    name: backend
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://localhost:3306/edu?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1348567319L.
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
      schema-locations: /sql/schema.sql
      data-locations: /sql/data.sql
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.edu.entity
